// <auto-generated />
namespace WebAdmin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class table_categoriaProdutos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_categoriaProdutos));
        
        string IMigrationMetadata.Id
        {
            get { return "201905051218459_table_categoriaProdutos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
